name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      hardhat:
        image: ethereum/client-go:v1.12.0
        ports:
          - 8545:8545
        command: ["--syncmode", "full"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Start Hardhat node
        run: |
          npx hardhat node &
          sleep 10

      - name: Deploy contract
        run: npx hardhat run scripts/deploy.js --network localhost

      - name: Run tests
        run: npm test

      - name: Debug Ethereum client
        run: docker logs $(docker ps -q --filter "ancestor=ethereum/client-go:v1.12.0")
